### ISSUE TITLE
Meta box

### ISSUE THREAD

**Issue by JanaME** [palasthotel/ph-postqueue#10]
Some customers ask for a meta box at post-edit to see, in which Postqueues the post is already in and to add and remove it to/from existing Postqueues.

Must be discussed with @EdwardBock, if this is a feature that we want to develop.

**Comment by EdwardBock** [comment]
@JanaME 

Should be an easy thing to do.

**Comment by JanaME** [comment]
Dearest @EdwardBock, I’m done here.
Could you please do a code review (a few commits the last days: https://github.com/palasthotel/ph-postqueue/commits/master) and check if we can roll it out to wordpress.org?

In addition to the metabox, I also added Internationalization and german translation and a few new functions in the Store Class.

**Comment by JanaME** [comment]
Memo:

- there is a bug when removing contents from postmeta box (sometimes the deleted content would appear twice in dropdown)

**Comment by JanaME** [comment]
@EdwardBock I fixed the bug. There was a problem with dublicate click-eventlisteners at the elements. Can you roll it out please? :) 🎢

**Comment by EdwardBock** [comment]
Looks great! Is released 🎉
