### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/ph-postqueue#4]
We got an bug report. I bet thats an multisite issue:

```
[Object, "parsererror", SyntaxError: Unexpected token < in JSON at position 0 at Object.parse (native) at n.parseJSO…]
in ph-postqueue-editor.js?ver=1.0.7:92
```

**Comment by DanielDeckerASMB** [comment]
FYI: I deactivated Multisite.

**Comment by EdwardBock** [comment]
TODO for me http://sudarmuthu.com/blog/how-to-properly-create-tables-in-wordpress-multisite-plugins/

**Comment by EdwardBock** [comment]
This issue has long been solved.
