### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by JanaME** [palasthotel/ph-postqueue#9]
To hook into that Postqueue-adding-and-removing-process, we might need a hook some day… 

- [ ]  action „postqueue_create_before“
- [ ] action „postqueue_create_after“

**Comment by EdwardBock** [comment]
What do you want to do before or after creating a postqueue? I'm just curious

**Comment by JanaME** [comment]
Not sure yet :D

**Comment by EdwardBock** [comment]
OK 😂
